### ISSUE TITLE
Ability to Verify List

### ISSUE THREAD

**Issue by mbovell** [cbush06/kosher#11]
SimpliTest has a "List" verification method, by defining a list or table, lists can be verified without the need to create a Scenario Outline.  Example Below:

 Scenario: Sanitize Reader Test Data
    Given I am on the "Readers" page
    And I should see "Readers"
    When I click the "Search" button
    Then I should be on the "Search_Readers" page
    And I should see the following list:
      **| Name                    | Facility                                        | Location         | Event Type |
      | AJ 7th Floor EDITED | Annapolis Junction Test Facility | NBP Entrance | Both           |**
    When I go to the "Edit_AJ_Reader" page
    Then I should see "Edit Reader"
    And I fill in "Name" with ""
    And I fill in "Name" with "AJ 7th Floor"
    # And I select "" from "FacilityId"
    And I select "Annapolis Junction Suite 700" from "LocationId"
    And I select "In" from "EventType"
    And I click the "Submit" button
    Then I should see "Readers"
    And I click the "Search" button
    And I should be on the "Search_Readers" page
    Then I should see the following list:
      **| Name         | Facility                         | Location                     | Event Type |
      | AJ 7th Floor | Annapolis Junction Test Facility | Annapolis Junction Suite 700 | In         |**
    And I take a screenshot

**Comment by cbush06** [comment]
Marlon,

The SimpliTest version of this step is only a dressed up version of its `I should see the following: ` step.

In essence, this step takes your example:

```gherkin
Then I should see the following list:
| Name         | Facility                         | Location                     | Event Type |
| AJ 7th Floor | Annapolis Junction Test Facility | Annapolis Junction Suite 700 | In         |
```

And converts it into this:
```gherkin
Then I should see all of the texts:
| Name                             |
| Facility                         |
| Location                         |
| Event Type                       |
| AJ 7th Floor                     |
| Annapolis Junction Test Facility |
| Annapolis Junction Suite 700     |
| In                               |
```

How would you like this step to work? I can think of 2 approaches:
1. Write it to work as SimpliTest did
2. Write it to verify that a table actually exists on the screen with cells that have matching content in the same order as provided by the test script

Obviously, the second option will be more complicated to implement and possibly more prone to bugs that need to be worked out. On the other hand, it might be slightly more useful. I'll leave it to you and Andrew to decide.

**Comment by skateoroma** [comment]
Thanks Clinton, 

Since this validation does not actually verify a value is actually in the stated field, no need to spend time adding it to your code base.  I'll use the Scenario Outline method.

Thanks
