### ISSUE TITLE
Find icon within table

### ISSUE THREAD

**Issue by rogers2111** [cbush06/kosher#37]
![image](https://user-images.githubusercontent.com/48539664/55167388-4560a400-5147-11e9-8101-0ab49fb74eab.png)

Ability to recognize icons and/or elements on a page

And I should see "Pending" in "Status"

Pending - would be a selector that points to the circled exclamation point icon
Status - would be a selector that would allow the entire status column to be verified

**Comment by cbush06** [comment]
Add step `Then the "<some_selector>" element should exist`

Allow it to be shortened to `Then "<some_selector>" should exist`
