### ISSUE TITLE
Select Drop Down List Verification Issue with Label

### ISSUE THREAD

**Issue by mbovell** [cbush06/kosher#38]
The step definition for the following statement does not verify the list when using value type = label;

Then "Person Type" should have the following options:
| Select 1 |
| Select 2 |
| Select 3 |

**Results file displays error:**
"error encountered while verifying options for [Person Type]: [%s] must be of type [select] but is [%s]%!(EXTRA string=Person Type, string=label)"

**Example Code:**
```
<div class="form-group">
<label>Person Type</label>
<select class="form-control" data-val="true" data-val-required="Person Type required." id="PersonType" name="PersonType"><option value=""></option>
<option value="1">Select 1</option>
<option value="2">Select 2</option>
<option value="3">Select 3</option>
</select>
</div>
```
EDIT: I believe the above error manifests when verifying "label" values with spaces, i.e.; 
```
<label>First Name</label> does not work
<label>FirstName</label> works
```

 - OS: [e.g. Windows 10]
 - Browser [ie]
 - Version [11.1.17134.0]

**Comment by cbush06** [comment]
The label is not connected to the element in this example. 

For example, this code above:
```html
<label>Person Type</label>
<select class="form-control" data-val="true" data-val-required="Person Type required." id="PersonType" name="PersonType">
...
</select>
```

Should be written like this (with the `for` attribute added to the `<label>` element):
```html
<label for="PersonType">Person Type</label>
<select class="form-control" data-val="true" data-val-required="Person Type required." id="PersonType" name="PersonType">
...
</select>
```

The reason using "PersonType" was working for you is kosher was matching that to the ID of the select list, not to the label.

If the `for` attribute is added to the `<label>` element, everything will work as expected.

**Comment by skateoroma** [comment]
Thanks @cbush06 I knew it worked because Kosher selected the id, but wasn't aware "for" should be used with the label element. I will let the developer know.
