### ISSUE TITLE
Support Creating Jira Tickets from Scenario Failures

### ISSUE THREAD

**Issue by cbush06** [cbush06/kosher#40]
**Describe the solution you'd like**
Allow creating Jira tickets from failed scenarios.

**Comment by rogers2111** [comment]
# Changes to the console (GitBash)
When initiating our tests we use the following command: Kosher run <file path to feature location> (i.e. Kosher run features/sprint1/logout.feature). We have already increased the functionality to include running tagged scenarios by inserting the (-T) command followed by the scenario “tag” (i.e. kosher run features/sprint1/logout.feature –t @first scenario) I would recommend adding the ability to call out when the user wishes to have kosher report to JIRA, this tag could be similar to the (-T) maybe (-J)?

After using the “-J” command in the console we would need to ensure Kosher will proceed in writing the JSON results to both the .html and to the console. When any deviations from the test scenarios have been identified the console will prompt the user to enter their JIRA credentials i.e. Username and Password, once the credentials have been authenticated the console will prompt the user for verification before creating the associated JIRA ticket. For example the console would read: Create “Bug” for logout.feature (failed scenario name) Y/N? When the user chooses the Y option the console will proceed into creating the “Issue” (Ticket).

* Associated changes to the settings.json file would be as follows:
Jira: {
    Host ”URL”
    Labels “labels that need to be added to the JIRA ticket”
    Type “Issue Type”
    Project Key “unique key associated to the users JIRA project”
    Description “Jira_Desc.txt”
}
* In this section, we can create another .txt file that will be given a name, much like the selectors. 
* Jira_Desc.txt will include the formatting template for the meat o the reporting within the associated ticket
  * H1 Expected Results
  * {steps to reproduce}
  * The steps for reproduction needs to include line numbers and mirror the actual test script
  * H1 Actual Results
  * Changes to the setting file will allow the user to make on the fly changes for their specific needs, therefore, eliminating downtime surrounding developer configurations
