### ISSUE TITLE
Did you ever get godog attachments working?

### ISSUE THREAD

**Issue by Johnlon** [cbush06/kosher#84]
**Is your feature request related to a problem? Please describe.**
Query.

Saw this ...
https://github.com/cbush06/kosher/blob/64f98bceae8028963353ddd6ea4538a61330aece/steps/websteps/browser_steps.go#L34

Looks like maybe you had a solution for making attachments work??

Any luck / advice / solution ?

Thanks

**Comment by cbush06** [comment]
Hi @Johnlon, I had to fork the project and add that feature. It was a minor change. Here's a link to my changes: https://github.com/cucumber/godog/compare/main...cbush06:godog:master
